spring:
  rabbitmq:
    addresses: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        concurrency: 1
        max-concurrency: 5
    
